/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Package = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'priceUsd' : IDL.Nat,
});
export const Time = IDL.Int;
export const Subscriber = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'fullName' : IDL.Text,
  'subscriptionStartDate' : Time,
  'phone' : IDL.Text,
  'packageId' : IDL.Nat,
});
export const BillingEntryView = IDL.Record({
  'year' : IDL.Nat,
  'months' : IDL.Vec(
    IDL.Record({ 'due' : IDL.Bool, 'month' : IDL.Nat, 'paid' : IDL.Bool })
  ),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPackage' : IDL.Func([IDL.Text, IDL.Nat], [Package], []),
  'createSubscriber' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, Time],
      [Subscriber],
      [],
    ),
  'getAllActiveSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], ['query']),
  'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getBillingState' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BillingEntryView)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPackage' : IDL.Func([IDL.Nat], [Package], ['query']),
  'getSubscriber' : IDL.Func([IDL.Text], [Subscriber], ['query']),
  'getSubscriberBillingSummary' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'totalOutstanding' : IDL.Nat,
          'totalPaid' : IDL.Nat,
          'totalDue' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getTotalDueForMonth' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], ['query']),
  'getTotalDueForYear' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setMonthBillingStatus' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool, IDL.Bool],
      [],
      [],
    ),
  'updatePackage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [Package], []),
  'updateSubscriber' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [Subscriber],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Package = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'priceUsd' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Subscriber = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'fullName' : IDL.Text,
    'subscriptionStartDate' : Time,
    'phone' : IDL.Text,
    'packageId' : IDL.Nat,
  });
  const BillingEntryView = IDL.Record({
    'year' : IDL.Nat,
    'months' : IDL.Vec(
      IDL.Record({ 'due' : IDL.Bool, 'month' : IDL.Nat, 'paid' : IDL.Bool })
    ),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPackage' : IDL.Func([IDL.Text, IDL.Nat], [Package], []),
    'createSubscriber' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, Time],
        [Subscriber],
        [],
      ),
    'getAllActiveSubscribers' : IDL.Func([], [IDL.Vec(Subscriber)], ['query']),
    'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getBillingState' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BillingEntryView)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPackage' : IDL.Func([IDL.Nat], [Package], ['query']),
    'getSubscriber' : IDL.Func([IDL.Text], [Subscriber], ['query']),
    'getSubscriberBillingSummary' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'totalOutstanding' : IDL.Nat,
            'totalPaid' : IDL.Nat,
            'totalDue' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getTotalDueForMonth' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Nat], ['query']),
    'getTotalDueForYear' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setMonthBillingStatus' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool, IDL.Bool],
        [],
        [],
      ),
    'updatePackage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [Package], []),
    'updateSubscriber' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [Subscriber],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };