/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BulkImportInput = IDL.Record({
  'names' : IDL.Text,
  'subscriptionStartDate' : Time,
  'packageId' : IDL.Nat,
});
export const Subscriber = IDL.Record({
  'id' : IDL.Nat,
  'active' : IDL.Bool,
  'fullName' : IDL.Text,
  'subscriptionStartDate' : Time,
  'phone' : IDL.Text,
  'packageId' : IDL.Nat,
});
export const BulkImportResult = IDL.Record({
  'result' : IDL.Opt(Subscriber),
  'name' : IDL.Text,
  'error' : IDL.Opt(IDL.Text),
});
export const Package = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'priceUsd' : IDL.Nat,
});
export const SubscriberResult = IDL.Record({
  'result' : IDL.Opt(Subscriber),
  'error' : IDL.Opt(IDL.Text),
});
export const DeleteAllSubscribersResult = IDL.Record({
  'subscribersDeleted' : IDL.Nat,
});
export const SubscriberMonthlyBill = IDL.Record({
  'fullName' : IDL.Text,
  'amountDue' : IDL.Nat,
});
export const MonthlyBillsResult = IDL.Record({
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'subscribers' : IDL.Vec(SubscriberMonthlyBill),
});
export const CallerPaymentDue = IDL.Record({
  'month' : IDL.Nat,
  'year' : IDL.Nat,
  'amountCents' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const SubscriberLoginInput = IDL.Record({
  'subscriberId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const SubscriberLoginResult = IDL.Record({
  'result' : IDL.Opt(Subscriber),
  'claimedPhone' : IDL.Opt(IDL.Text),
  'error' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkCreateSubscribers' : IDL.Func(
      [BulkImportInput],
      [IDL.Vec(BulkImportResult)],
      [],
    ),
  'createPackage' : IDL.Func([IDL.Text, IDL.Nat], [Package], []),
  'createSubscriber' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, Time],
      [SubscriberResult],
      [],
    ),
  'deleteAllSubscribers' : IDL.Func([], [DeleteAllSubscribersResult], []),
  'fetchMonthlyBills' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [MonthlyBillsResult],
      ['query'],
    ),
  'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
  'getCallerMonthlyDue' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [CallerPaymentDue],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPackage' : IDL.Func([IDL.Nat], [Package], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isPhoneNumberTaken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'loginClaimSubscriber' : IDL.Func(
      [SubscriberLoginInput],
      [SubscriberLoginResult],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePackage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [Package], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BulkImportInput = IDL.Record({
    'names' : IDL.Text,
    'subscriptionStartDate' : Time,
    'packageId' : IDL.Nat,
  });
  const Subscriber = IDL.Record({
    'id' : IDL.Nat,
    'active' : IDL.Bool,
    'fullName' : IDL.Text,
    'subscriptionStartDate' : Time,
    'phone' : IDL.Text,
    'packageId' : IDL.Nat,
  });
  const BulkImportResult = IDL.Record({
    'result' : IDL.Opt(Subscriber),
    'name' : IDL.Text,
    'error' : IDL.Opt(IDL.Text),
  });
  const Package = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'priceUsd' : IDL.Nat,
  });
  const SubscriberResult = IDL.Record({
    'result' : IDL.Opt(Subscriber),
    'error' : IDL.Opt(IDL.Text),
  });
  const DeleteAllSubscribersResult = IDL.Record({
    'subscribersDeleted' : IDL.Nat,
  });
  const SubscriberMonthlyBill = IDL.Record({
    'fullName' : IDL.Text,
    'amountDue' : IDL.Nat,
  });
  const MonthlyBillsResult = IDL.Record({
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'subscribers' : IDL.Vec(SubscriberMonthlyBill),
  });
  const CallerPaymentDue = IDL.Record({
    'month' : IDL.Nat,
    'year' : IDL.Nat,
    'amountCents' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const SubscriberLoginInput = IDL.Record({
    'subscriberId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'phone' : IDL.Text,
  });
  const SubscriberLoginResult = IDL.Record({
    'result' : IDL.Opt(Subscriber),
    'claimedPhone' : IDL.Opt(IDL.Text),
    'error' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkCreateSubscribers' : IDL.Func(
        [BulkImportInput],
        [IDL.Vec(BulkImportResult)],
        [],
      ),
    'createPackage' : IDL.Func([IDL.Text, IDL.Nat], [Package], []),
    'createSubscriber' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, Time],
        [SubscriberResult],
        [],
      ),
    'deleteAllSubscribers' : IDL.Func([], [DeleteAllSubscribersResult], []),
    'fetchMonthlyBills' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [MonthlyBillsResult],
        ['query'],
      ),
    'getAllPackages' : IDL.Func([], [IDL.Vec(Package)], ['query']),
    'getCallerMonthlyDue' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [CallerPaymentDue],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPackage' : IDL.Func([IDL.Nat], [Package], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isPhoneNumberTaken' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'loginClaimSubscriber' : IDL.Func(
        [SubscriberLoginInput],
        [SubscriberLoginResult],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePackage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [Package], []),
  });
};

export const init = ({ IDL }) => { return []; };